version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '5000:5000'
      - '5001:5001'
    links:
      - 'db:database'
  db:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_PASSWORD: mss-dev
